### ISSUE TITLE
npm run start fails because foreman is not available in package.json

### ISSUE THREAD

**Issue by anusha5695** [Orrison/Larval#20]

**Comment by anusha5695** [comment]
Hi @Orrison : Can you please verify this : https://github.com/Orrison/Larval/pull/21

**Comment by Orrison** [comment]
Hey @anusha5695 I have not seen this error come through before. Would you mind posting the stacktrace or the errors you are seeing?

**Comment by anusha5695** [comment]
Hi @Orrison : Please find the log below
![image](https://user-images.githubusercontent.com/33545283/68036280-5aa83d00-fceb-11e9-8336-c09ccfa3e646.png)

**Comment by Orrison** [comment]
Closed by merge of PR #21
